# Generated by Django 3.2.7 on 2021-10-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_buyerpurchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerpurchase',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='buyerpurchase',
            old_name='product_id',
            new_name='product',
        ),
    ]
