# Generated by Django 3.2.7 on 2021-10-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_deposit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
